FROM golang:1.23-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o partojshid .

# Final image
FROM alpine:3.20
RUN apk add --no-cache ca-certificates tzdata
COPY --from=builder /app/partojshid /usr/local/bin/partojshid
COPY --from=builder /app/.env.example /.env

EXPOSE 8080
CMD ["partojshid"]